### PR TITLE
custom category in experiment

### PR DESCRIPTION
**Pull request by scardinius**

### CODE REVIEW

**Comment by gingerlime** [comment]
Thanks for the PR @scardinius. It's great to see interest and contributions!

A few things however:

* could you explain this change?
* you've made changes to the compiled version under `dist`. The "real" source is the coffeescript files under the root folder. Any changes should therefore go in there (typically `alephbet.js.coffee`), and then get compiled / built via `npm build`.

**Comment by gingerlime** [comment]
Another thing - the default tracking adapter is just meant to be a placeholder. You can however easily implement your own adapter and do whatever you need with it. see https://github.com/gingerlime/alephbet#custom-tracking-adapter for more info. So whilst I'm happy to update the default adapter if it makes sense, the idea is that when you use AlephBet, you can/should use your own adapter.

**Comment by tttp** [comment]
Hi,
The rationale is that when storing the events in google analytics, they are several domains that might run tests, so to avoid a collision between two tests having the same name but different tracking, it would be useful to change the default "alephbet" by something unique (eg. "main site", "blog", "french site"...) so if each of them have a "home page" experiment, it won't mess up things on the tracking)

**Comment by gingerlime** [comment]
The default analytics tracking adapter already has a namespace, which you could overwrite. If you need to tweak the adapter further, you can.

**Comment by gingerlime** [comment]
I'm going to close this one for now, but happy to keep discussing this or help you with the build process, so the changes are reflected on the coffeescript files.

**Comment by scardinius** [comment]
I wrote own adapter as you suggested. Thanks for you help.

```javascript
  var custom_adapter = (function(namespace) {

    this.namespace = namespace || 'alephbet';

    this._track = function(category, action, label, value) {
      if (typeof ga !== 'function') {
        throw 'ga not defined. Please make sure your Universal analytics is set up correctly';
      }
      return ga('send', 'event', category, action, label, value);
    };

    this.experiment_start = function(experiment_name, variant) {
      return this._track(this.namespace, experiment_name, variant + " | views");
    };

    this.goal_complete = function(experiment_name, variant, event_name) {
      return this._track(this.namespace, experiment_name, variant + " | goal | " + event_name);
    };

    return this;
    
  });

  var experiment = new AlephBet.Experiment({
    name: 'experiment-name', 
    variants: {
    // variants
    },
    tracking_adapter: custom_adapter('custom-category')
  });
```

**Comment by gingerlime** [comment]
That's great! Thanks for sharing and glad to hear you could get things going.

**Pull request closed without merging**
